<a href="https://colab.research.google.com/github/erSASD/machine_learning/blob/main/01_wprowadzenie/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


3D array


In [2]:
x = np.array(
    [[[4,3,1]]]
)
x

array([[[4, 3, 1]]])

In [3]:
x.ndim

3

In [5]:
x.shape

(1, 1, 3)

Typy danych

In [6]:
a = np.array([0, 1.0, 2.3, 3.3], dtype=np.int8)
a.dtype
a

array([0, 1, 2, 3], dtype=int8)

Tworzenie tablic

In [11]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
np.ones(shape=(4,10), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(start=5, stop=100, step =5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [17]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [22]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [23]:
A + B

array([6, 0, 7, 4])

In [24]:
A - B

array([0, 2, 1, 0])

In [25]:
A * B

array([ 9, -1, 12,  4])

In [26]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [27]:
A + 3

array([6, 4, 7, 5])

In [28]:
A - 3

array([ 0, -2,  1, -1])

In [29]:
A + 3*B

array([12, -2, 13,  8])

In [30]:
np.add(A,B)

array([6, 0, 7, 4])

In [32]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [33]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [34]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [36]:
X = np.array([[1, 3], [-2,0]])
Y = np.array([[6,0], [-1,2]])


In [37]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [38]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

Generowanie licz pseudolosowych

In [51]:
np.random.seed(0)

In [55]:
np.random.randn(10,4)

array([[-0.26731719, -0.54930901,  0.1327083 , -0.47614201],
       [ 1.30847308,  0.19501328,  0.40020999, -0.33763234],
       [ 1.25647226, -0.7319695 ,  0.66023155, -0.35087189],
       [-0.93943336, -0.48933722, -0.80459114, -0.21269764],
       [-0.33914025,  0.31216994,  0.56515267, -0.14742026],
       [-0.02590534,  0.2890942 , -0.53987907,  0.70816002],
       [ 0.84222474,  0.2035808 ,  2.39470366,  0.91745894],
       [-0.11227247, -0.36218045, -0.23218226, -0.5017289 ],
       [ 1.12878515, -0.69781003, -0.08112218, -0.52929608],
       [ 1.04618286, -1.41855603, -0.36249918, -0.12190569]])

In [62]:
np.random.rand(10, 2)

array([[0.59783665, 0.26221566],
       [0.30087131, 0.02539978],
       [0.30306256, 0.24207588],
       [0.55757819, 0.56550702],
       [0.47513225, 0.29279798],
       [0.06425106, 0.97881915],
       [0.33970784, 0.49504863],
       [0.97708073, 0.44077382],
       [0.31827281, 0.51979699],
       [0.57813643, 0.85393375]])

In [73]:
np.random.randint(10)

9

In [77]:
np.random.randint(low=10, high=101, size=(10,10))

array([[ 86,  78,  40,  80,  84,  40,  19,  12,  75,  23],
       [ 85,  62,  15,  94,  58,  72,  52,  44,  50,  56],
       [ 42,  96,  68,  79,  55,  28,  60,  54,  11,  73],
       [ 87,  28,  37,  93,  47,  81,  98,  25,  65,  16],
       [ 54,  19,  60,  10,  54,  78,  24,  14,  16,  52],
       [ 83,  54, 100,  48,  30,  19,  50,  26,  85,  49],
       [ 68,  91,  49,  59,  21,  88,  89,  31,  79,  58],
       [ 70,  68,  23,  13,  41,  86,  97,  27,  39,  79],
       [ 60,  61,  30,  15,  80,  71,  26,  84,  14,  32],
       [ 29,  95,  83,  45,  45,  21,  51,  64,  92,  29]])

In [78]:
np.random.choice([4,2,1,3,2])

2

In [81]:
dataa = np.arange(10)
dataa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.random.shuffle(dataa)
dataa

array([6, 9, 8, 2, 7, 5, 3, 0, 4, 1])

Podstawowe funckje w języky python

In [83]:
np.exp(1)

2.718281828459045

In [84]:
np.sqrt(9)

3.0

In [87]:
np.all([2,3,1])

True

In [89]:
np.any([0,0,1])

True

In [90]:
bool(0)

False

In [91]:
A = np.random.rand(5)
A

array([0.20595026, 0.57377623, 0.29383156, 0.65572674, 0.80356835])

In [92]:
np.argmax(A)

4

In [94]:
A[np.argmax(A)]

0.8035683477432196

In [95]:
np.argmin(A)

0

In [96]:
np.argsort(A)

array([0, 2, 1, 3, 4])

In [97]:
np.max(A)

0.8035683477432196

In [98]:
np.mean(A)

0.506570627096352

In [99]:
np.median(A)

0.5737762314512022

In [100]:
np.std(A)

0.22387599467382058

Indeksowanie

In [101]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [103]:
# A[idx], A[start:stop], A[:stop], A[Start:]
A[2]

2

In [104]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [106]:
A[2:5]

array([2, 3, 4])

In [105]:
A[:2]

array([0, 1])

In [107]:
A[-1]

19

In [109]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
A[0]

array([0, 1, 2, 3, 4])

In [111]:
A[:,0]

array([ 0,  5, 10, 15])

In [112]:
A[:,-1]

array([ 4,  9, 14, 19])

In [115]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [116]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [117]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [118]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [120]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [121]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [122]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [128]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [129]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [131]:
A = np.arange(start=-10, stop=10, step=0.5)
A.reshape(10, -1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [132]:
A > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [133]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [136]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [137]:
A[np.bitwise_or(A > -5, A < 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])